### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by RobinRMC** [Ro-Chat/rath#1]
I can't seem to get it to work.

Is this functional yet? What is the prefix?

It looks very promising, but it just doesn't do anything.

**Comment by Ro-Chat** [comment]
It seems to work fine for me. the prefix is ;

**Comment by RobinRMC** [comment]
This is for Prison Life, correct?

**Comment by RobinRMC** [comment]
I now get errors saying "You cannot whisper to yourself."

The errors are constantly repeating.

**Comment by Ro-Chat** [comment]
The toggleSiren remote was removed use a different script.

**Comment by RobinRMC** [comment]
So unfortunate that an update releases that fixes your problem a day after you made this.
